- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: HEAD
  hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: no-commit-to-branch
      args:
        [
          "--pattern",
          "master",
          "--pattern",
          "release/.*",
          "--pattern",
          "develop/.*",
        ]

- repo: https://github.com/ambv/black
  rev: HEAD
  hooks:
    - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: HEAD
  hooks:
    - id: flake8
