repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: HEAD
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: no-commit-to-branch
        args:
          [
            "--pattern",
            "master",
            "--pattern",
            "release/.*",
            "--pattern",
            "develop/.*",
          ]
  - repo: git://github.com/golangci/golangci-lint
    rev: HEAD
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go.
        types: [go]
        language: golang
        pass_filenames: false
